### ISSUE TITLE
`localStorage` access denied when "Block third-party cookies" is enabled in Chrome

### ISSUE THREAD

**Issue by toolatetotheparty** [metarmask/dom-distiller-reading-mode#18]
Could the extension be modified in such a way so it could work with third-party cookies blocked?
https://i.imgur.com/Ng3SSf9.png

**Comment by metarmask** [comment]
The reason the extension uses localStorage as opposed to chrome.runtime.sendMessage or chrome.storage API is because it is synchronous and should therefore prevent a flash of white if the dark theme is enabled. Read [this comment](https://github.com/metarmask/dom-distiller-reading-mode/issues/4#issuecomment-372096758) for a workaround, and the bug which causes this that you can vote on.

I worked a bit on porting the extension to Firefox. In that new version the part that displays the result gets its own tab, which should prevent this issue.

**Comment by toolatetotheparty** [comment]
Sorry for duplication.
